:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  # Queue priority: https://github.com/mperham/sidekiq/wiki/Advanced-Options
  - default
  # - mailers
:schedule:
  AllremindersJob:
    # Runs every day at midnight
    cron: '0 23 * * *'
    queue: scheduler
    enabled: true
